theme: "modern"
skin: "light"
toolbar:
  - styleselect | bold underline italic | bullist numlist | undo redo | image | link | code
plugins:
  - image
  - link
  - media
  - bbcode
  - code
  - colorpicker
  - emoticons
  - hr
  - table
